### ISSUE TITLE
Windows: Julia 64 bit vs GMAT 32 bit

### ISSUE THREAD

**Issue by loicspace** [JuliaSpace/GMAT.jl#2]
Hi!

Thanks for the package, it is awesome!
I'm however trying to port my software from Linux to Windows and I'm now seeing that -- for some reason -- GMAT is only released in 32 bit for Windows. So my issue is not as much with Julia as it is with GMAT but I figured you might have some insight...

Does that mean I need to use a 32 bit Julia install as well to make this work?
I did go that route to try it out but that breaks some other packages my software depends on, some don't seem to like running in 32 bit at all, or running a 32 bit version on a 64 bit machine, either way, a bunch of things break....

Thanks,
Loic

**Comment by helgee** [comment]
You are correct, you need a 32 bit Julia. Apart from that I do not have much advice to offer, I am afraid.

**Comment by loicspace** [comment]
Argh I was afraid you'd say that. 
I may try to build a 64b GMAT from source and see if I can link that to your package. Experience -- and lack thereof -- with building NASA software on Windows tells me this may not get me anywhere tho.

I'm also going to post on the GMAT forum/email them regarding why it is not distributed as binary.

Thanks for the reply!

**Comment by helgee** [comment]
Have you opened a thread for this? I could not find it and would be interested in the answer as well.

**Comment by helgee** [comment]
For reference: We should try to to build our own GMAT binaries via https://github.com/JuliaPackaging/BinaryBuilder.jl

**Comment by loicspace** [comment]
Hi!
Apologies, I only now have the chance to worry about that problem again...
I never got the chance to post on the GMAT forum as I can't seem to receive any activation email...and I tried a couple different email accounts, SPAM filters,...

That Julia package does look interesting tho!

**Comment by helgee** [comment]
I have used it successfully just yesterday to build new binaries for [ERFA](https://github.com/JuliaAstro/ERFABuilder) and [CSPICE](https://github.com/JuliaAstro/SPICEBuilder). Since it is a cross-compilation environment, I am not sure how a GUI application like GMAT will react to it but I will certainly try it.

**Comment by helgee** [comment]
Notes to self:
* Use a source zip from SF because the Git repo is stuck in 2014 e.g. https://downloads.sourceforge.net/project/gmat/GMAT/GMAT-R2017a/GMAT-src_and_data-R2017a.zip
* The CMake version requirement is set too high. Downgrade: `sed -i 's/cmake_minimum_required(VERSION 3.7.0)/cmake_minimum_required(VERSION 3.6.3)'`
* The build is not configurable at all but it might be possible to just comment out the wxWidgets and GUI subproject related lines
* Their build of CSPICE fails but precompiled binaries might work (https://github.com/JuliaAstro/SPICEBuilder)

**Comment by helgee** [comment]
Oh boy, what a mess. Building GMAT as a library would require some serious hacking (and cleaning up) of the build system.
